version: 0.2
       
phases:
  install:
    commands:
      - echo Downloading and installing Composer...
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php
      - rm composer-setup.php
      - mv composer.phar /usr/local/bin/composer
  build:
    commands:
      - echo Downloading Projects Dependencies...
      - composer install
 