version: 0.2
       
phases:
  install:
    commands:
      - |
          echo Downloading and installing Composer...
          apt-get install -y git
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          rm composer-setup.php
          mv composer.phar /usr/local/bin/composer
  build:
    commands:
      - |
          echo Downloading Projects Dependencies...
          composer install

  post_build:
    commands:
      - |
          echo Unit Testing
          ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/BasicTest.php
          
artifacts:
  files:
    - '**/*'

  discard-paths: no # remember to test this the same would be remove the line
 